DROP TABLE IF EXISTS "RECIPE";
DROP TABLE IF EXISTS "DOCTOR";
DROP TABLE IF EXISTS "PATIENT";

-- region Doctor
CREATE TABLE "DOCTOR"
(
    "ID"             BIGINT PRIMARY KEY NOT NULL,
    "NAME"           VARCHAR(255)       NOT NULL,
    "LASTNAME"       VARCHAR(255)       NOT NULL,
    "SURNAME"        VARCHAR(255)       NOT NULL,
    "SPECIALIZATION" VARCHAR(255)       NOT NULL
);
-- GRANT SELECT ON DOCTOR TO PUBLIC;
-- endregion

-- region Patient
CREATE TABLE "PATIENT"
(
    "ID"          BIGINT PRIMARY KEY NOT NULL,
    "NAME"        VARCHAR(255)       NOT NULL,
    "LASTNAME"    VARCHAR(255)       NOT NULL,
    "SURNAME"     VARCHAR(255)       NOT NULL,
    "PHONENUMBER" VARCHAR(255)       NOT NULL
);
-- GRANT SELECT ON PATIENT TO PUBLIC;
-- endregion

-- region Recipe
CREATE TABLE "RECIPE"
(
    "ID"          BIGINT PRIMARY KEY NOT NULL,
    "DESCRIPTION" VARCHAR(255)       NOT NULL,
    "ID_PATIENT"  BIGINT             NOT NULL,
    "ID_DOCTOR"   BIGINT             NOT NULL,
    "CREATEDATE"  DATE               NOT NULL,
    "VALIDITY"    DATE               NOT NULL,
    "PRIORITY"    VARCHAR(255)       NOT NULL,
    FOREIGN KEY (ID_DOCTOR) REFERENCES DOCTOR (ID),
    FOREIGN KEY (ID_PATIENT) REFERENCES PATIENT (ID)
);
-- GRANT SELECT ON RECIPE TO PUBLIC;
-- endregion

